variables:
  ${{ if startsWith(variables['build.sourceBranch'], 'refs/tags/v') }}:
    IS_RELEASE: true
  ${{ if not(startsWith(variables['build.sourceBranch'], 'refs/tags/v')) }}:
    IS_RELEASE: false

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  tags:
    include:
    - 'v*'

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
- job: 'WebAssembly'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: "azure-templates/webassembly.yml"

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      Python27ManyLinux2010:
        python.version: '2.7'
        python_flag: '--python2'
        manylinux_flag: '--manylinux2010'
        artifact_name: 'cp27-cp27m-manylinux2010_x86_64'
      Python37ManyLinux2010:
        python.version: '3.7'
        python_flag: ''
        manylinux_flag: '--manylinux2010'
        artifact_name: 'cp37-cp37m-manylinux2010_x86_64'

      ${{ if eq(variables.IS_RELEASE, true) }}:
        Python36ManyLinux2010:
          python.version: '3.6'
          python_flag: '--python36'
          manylinux_flag: '--manylinux2010'
          artifact_name: 'cp36-cp36m-manylinux2010_x86_64'
        Python36ManyLinux2014:
          python.version: '3.6'
          python_flag: '--python36'
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp36-cp36m-manylinux2014_x86_64'
        # Python37ManyLinux2010 is always built
        Python37ManyLinux2014:
          python.version: '3.7'
          python_flag: ''
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp37-cp37m-manylinux2014_x86_64'
        Python38ManyLinux2010:
          python.version: '3.8'
          python_flag: '--python38'
          manylinux_flag: '--manylinux2010'
          artifact_name: 'cp38-cp38-manylinux2010_x86_64'
        Python38ManyLinux2014:
          python.version: '3.8'
          python_flag: '--python38'
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp38-cp38-manylinux2014_x86_64'

  steps:
    - template: "azure-templates/linux.yml"

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        python_flag: ''
      ${{ if eq(variables.IS_RELEASE, true) }}:
        Python36:
          python.version: '3.6'
          python_flag: '--python36'
        Python38:
          python.version: '3.8'
          python_flag: '--python38'

  steps:
    - template: "azure-templates/windows.yml"

- job: 'MacOS_Catalina'
  pool:
    vmImage: 'macos-10.15'

  strategy:
    matrix:

      Python27:
        python.version: '2.7'
        python_flag: '--python2'
        artifact_name: 'cp27-cp27m-macosx_10_15_x86_64'

      Python37:
        python.version: '3.7'
        python_flag: ''
        artifact_name: 'cp37-cp37m-macosx_10_15_x86_64'

      ${{ if eq(variables.IS_RELEASE, true) }}:
        Python36:
          python.version: '3.6'
          python_flag: '--python36'
          artifact_name: 'cp36-cp36m-macosx_10_15_x86_64'
  
        Python38:
          python.version: '3.8'
          python_flag: '--python38'
          artifact_name: 'cp38-cp38-macosx_10_15_x86_64'

  steps:
    - template: "azure-templates/macos.yml"
    
# - job: 'MacOS_Mojave'
#   pool:
#     vmImage: 'macos-10.14'

#   strategy:
#     matrix:
#       Python37:
#         python.version: '3.7'
#         python_flag: ''
#         artifact_name: 'cp37-cp37m-macosx_10_14_x86_64'

#       ${{ if eq(variables.IS_RELEASE, true) }}:
#         Python27:
#           python.version: '2.7'
#           python_flag: '--python2'
#           artifact_name: 'cp27-cp27m-macosx_10_14_x86_64'

#         Python36:
#           python.version: '3.6'
#           python_flag: '--python36'
#           artifact_name: 'cp36-cp36m-macosx_10_14_x86_64'

#         Python38:
#           python.version: '3.8'
#           python_flag: '--python38'
#           artifact_name: 'cp38-cp38-macosx_10_14_x86_64'

#   steps:
#     # only build python37 if not a release
#     - ${{ if or(eq(variables.IS_RELEASE, true), eq(variables['python_flag'], '')) }}:
#       - template: "azure_pipelines/macos.yml"